# Generated by Django 4.0.5 on 2022-07-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='songs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trlr',
            field=models.TextField(null=True),
        ),
    ]
