# Generated by Django 4.0.5 on 2022-07-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_songs_movie_trlr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trlr',
        ),
    ]
